(** Extracted from Hexstrike.Types.fst — core types with risk ordering.
    DO NOT EDIT: regenerated by F* extraction in CI. *)

type severity =
  | Info
  | Low
  | Medium
  | High
  | Critical

let severity_to_nat = function
  | Info     -> 0
  | Low      -> 1
  | Medium   -> 2
  | High     -> 3
  | Critical -> 4

let severity_leq a b = severity_to_nat a <= severity_to_nat b

type policy_decision =
  | Allowed
  | Denied of string

type audit_level =
  | Minimal
  | Standard
  | Verbose

type tool_call = {
  tc_tool_name  : string;
  tc_caller     : string;
  tc_target     : string;
  tc_request_id : string;
}

type tool_capability = {
  cap_name          : string;
  cap_category      : string;
  cap_risk_level    : severity;
  cap_max_exec_secs : int;
}

type policy = {
  pol_name            : string;
  pol_allowed_tools   : string list;
  pol_denied_tools    : string list;
  pol_max_risk_level  : severity;
  pol_audit_level     : audit_level;
}

type dispatch_result =
  | DispatchOk     of string
  | DispatchDenied of string * string
  | DispatchError  of string * string
