(** Extracted from Hexstrike.Dispatch.fst — verified dispatch engine.
    DO NOT EDIT: regenerated by F* extraction in CI. *)

open Hexstrike_Types
open Hexstrike_Audit

type registry = (string * tool_capability) list

let rec lookup name = function
  | [] -> None
  | (n, cap) :: tl -> if n = name then Some cap else lookup name tl

type dispatch_outcome = {
  do_result : dispatch_result;
  do_audit  : audit_entry;
}

let dispatch reg pol tc ~prev_hash ~entry_id ~timestamp =
  match lookup tc.tc_tool_name reg with
  | None ->
    let reason = "unknown tool: " ^ tc.tc_tool_name in
    let result = DispatchError (tc.tc_tool_name, reason) in
    let audit = create_entry ~entry_id ~prev_hash ~timestamp
      ~caller:tc.tc_caller ~tool_name:tc.tc_tool_name
      ~decision:(Denied reason) ~risk:Info ~duration:0 ~result:reason in
    { do_result = result; do_audit = audit }
  | Some cap ->
    match Hexstrike_Sanitize.sanitize tc.tc_target with
    | None ->
      let reason = "target contains shell metacharacters" in
      let result = DispatchDenied (tc.tc_tool_name, reason) in
      let audit = create_entry ~entry_id ~prev_hash ~timestamp
        ~caller:tc.tc_caller ~tool_name:tc.tc_tool_name
        ~decision:(Denied reason) ~risk:cap.cap_risk_level ~duration:0
        ~result:reason in
      { do_result = result; do_audit = audit }
    | Some _clean_target ->
      let decision = Hexstrike_Policy.evaluate_policy pol tc cap in
      (match decision with
       | Denied reason ->
         let result = DispatchDenied (tc.tc_tool_name, reason) in
         let audit = create_entry ~entry_id ~prev_hash ~timestamp
           ~caller:tc.tc_caller ~tool_name:tc.tc_tool_name
           ~decision ~risk:cap.cap_risk_level ~duration:0 ~result:reason in
         { do_result = result; do_audit = audit }
       | Allowed ->
         let result = DispatchOk tc.tc_tool_name in
         let audit = create_entry ~entry_id ~prev_hash ~timestamp
           ~caller:tc.tc_caller ~tool_name:tc.tc_tool_name
           ~decision:Allowed ~risk:cap.cap_risk_level ~duration:0
           ~result:"dispatched" in
         { do_result = result; do_audit = audit })
