(** Extracted from Hexstrike.Sanitize.fst — input sanitization.
    DO NOT EDIT: regenerated by F* extraction in CI. *)

let shell_metachars =
  [ '|'; '&'; ';'; '$'; '`'; '('; ')'; '{'; '}'; '<'; '>'; '\n'; '\r' ]

let is_shell_meta c = List.mem c shell_metachars

let has_shell_meta s =
  let len = String.length s in
  let rec check i =
    if i >= len then false
    else if is_shell_meta s.[i] then true
    else check (i + 1)
  in
  check 0

let sanitize s =
  if has_shell_meta s then None
  else Some s
