(** Extracted from Hexstrike.Audit.fst — hash-chain audit log.
    DO NOT EDIT: regenerated by F* extraction in CI.
    Requires Hexstrike_Extern.sha256 for the external sha256 function. *)

open Hexstrike_Types

type audit_entry = {
  ae_entry_id      : string;
  ae_previous_hash : string;
  ae_timestamp     : string;
  ae_caller        : string;
  ae_tool_name     : string;
  ae_decision      : policy_decision;
  ae_risk_level    : severity;
  ae_duration_ms   : int;
  ae_result        : string;
  ae_entry_hash    : string;
}

let entry_payload e =
  String.concat "|" [
    e.ae_entry_id;
    e.ae_previous_hash;
    e.ae_timestamp;
    e.ae_caller;
    e.ae_tool_name;
    (match e.ae_decision with
     | Allowed -> "allowed"
     | Denied r -> "denied:" ^ r);
    string_of_int (severity_to_nat e.ae_risk_level);
    string_of_int e.ae_duration_ms;
    e.ae_result;
  ]

let verify_entry e =
  e.ae_entry_hash = Hexstrike_Extern.sha256 (entry_payload e)

let verify_chain_link ~prev ~curr =
  curr.ae_previous_hash = prev.ae_entry_hash && verify_entry curr

let create_entry ~entry_id ~prev_hash ~timestamp
    ~caller ~tool_name ~decision ~risk ~duration ~result =
  let e_partial = {
    ae_entry_id      = entry_id;
    ae_previous_hash = prev_hash;
    ae_timestamp     = timestamp;
    ae_caller        = caller;
    ae_tool_name     = tool_name;
    ae_decision      = decision;
    ae_risk_level    = risk;
    ae_duration_ms   = duration;
    ae_result        = result;
    ae_entry_hash    = "";
  } in
  let hash = Hexstrike_Extern.sha256 (entry_payload e_partial) in
  { e_partial with ae_entry_hash = hash }

let genesis_hash =
  String.make 64 '0'
