(** Extracted from Hexstrike.Policy.fst — policy evaluation.
    DO NOT EDIT: regenerated by F* extraction in CI. *)

open Hexstrike_Types

let rec mem x = function
  | [] -> false
  | hd :: tl -> if hd = x then true else mem x tl

let evaluate_policy pol tc cap =
  if mem tc.tc_tool_name pol.pol_denied_tools then
    Denied "tool is explicitly denied by policy"
  else if not (severity_leq cap.cap_risk_level pol.pol_max_risk_level) then
    Denied "tool risk level exceeds policy maximum"
  else
    match pol.pol_allowed_tools with
    | [] -> Allowed
    | _ ->
      if mem tc.tc_tool_name pol.pol_allowed_tools then
        Allowed
      else
        Denied "tool is not in the allowed list"
